### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by Thelin90** [oslabs-beta/Kafkasocks#49]
Hello.

I am currently trying out your project.

Currently when I do:

`package.json`
```yaml
{
  "name": "kafka-to-socket",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "tsc": "./node_modules/typescript/bin/tsc",
    "build": "tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^12.20.37",
    "typescript": "^4.5.3"
  },
  "dependencies": {
    "kafka-socks": "0.1.10",
    "ts-node": "^10.4.0"
  }
}
```

And when I add:

```javascript
import { Confluent, Consumer, Subject } from 'kafka-socks';

const express = require('express');
const http = require('http');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

const KAFKA_BOOTSTRAP_SERVER = ['localhost:31659']
const kafka = new Confluent(KAFKA_BOOTSTRAP_SERVER).create("client-id");

const kafkaConsumer = kafka.consumer({ groupId:  "test-group" });
const kafkaSocksConsumer = new Consumer(kafkaConsumer, "topic", 'websocket-event-ID')
const kafkaSocksSubject = new Subject(io, 'websocket-namespace-ID')
```

I get this error:

![image](https://user-images.githubusercontent.com/19892351/145736462-009332d2-4a49-4bbc-87fd-6399d7278337.png)

I am day to day, not working with JS or typescript so I am a bit confused here?

I tried to install the `type` but don't think this exists.

```bash
npm i --save-dev @types/kafka-socks 
```

```bash
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fkafka-socks - Not found
npm ERR! 404 
npm ERR! 404  '@types/kafka-socks@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simon/.npm/_logs/2021-12-13T00_43_05_792Z-debug.log
```

Is this something you have seen before?
